### ISSUE TITLE
Monospace itself - too wide overall in the family as a whole?

### ISSUE THREAD

**Issue by EbenSorkin** [aoifemooney/cutivemono#11]
This is a question that could of course be ignored because it is so fundamental and would create wholesale change in the design. But to my eye when text is set in all styles it feels almost comically widely set. Like a parody of a monospace. The common width now is 1240. For example if you remove 60 units on either side the text begins to look much more like what you expect and reading it is much more comfortable. Applying it globally does mess up some relationships to anchors so if it is done it should be a bit more surgical than my test was.

**Comment by EbenSorkin** [comment]
Aofie & Dave I'll send you my altered glyphs file so you can see for your self in a paragraph.

**Comment by aoifemooney** [comment]
discussed with Dave & Eben, but thinking we will leave the cartoonish width for now, since deviating would be too big of a change from original design. Shelving for future so it will not disrupt existing users who might be using tracked currently.
