### ISSUE TITLE
idotbelow - I am puzzled about why the dot below is s much lighter than the one on i

### ISSUE THREAD

**Issue by EbenSorkin** [aoifemooney/cutivemono#17]
I tend to think that the dot should be the same or nearly so. What do you think? Why?

Also idotaccent has a light dot too.

**Comment by aoifemooney** [comment]
agreed, i think this was unintentional, actually, i think perhaps the dot accent form did not get updated, the difference is so small, particularly in the light weights, that it makes no sense for them to be different. Updated.
